version: '3.7'

services:
  zookeeper-event-1:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-event-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-event-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

#  kafka-event-1:
#    image: confluentinc/cp-kafka:7.5.0
#    depends_on:
#      - zookeeper-event-1
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-event-1:2181
#      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-event-1:9092, EXTERNAL://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#      KAFKA_NUM_PARTITIONS: 3
#    ports:
#      - "9092:9093"
#
#  kafka-event-2:
#    image: confluentinc/cp-kafka:7.5.0
#    depends_on:
#      - zookeeper-event-1
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-event-1:2181
#      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-event-2:9092, EXTERNAL://localhost:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#      KAFKA_NUM_PARTITIONS: 3
#    ports:
#      - "9093:9093"
#
#  kafka-event-3:
#    image: confluentinc/cp-kafka:7.5.0
#    depends_on:
#      - zookeeper-event-1
#    environment:
#      KAFKA_BROKER_ID: 3
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-event-1:2181
#      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-event-3:9092, EXTERNAL://localhost:9094
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#      KAFKA_NUM_PARTITIONS: 3
#    ports:
#      - "9094:9093"